### ISSUE TITLE
No Class Definition Found For com/facebook/stetho/okhttp/StethoInterceptor

### ISSUE THREAD

**Issue by dcrelling** [facebook/stetho#524]
HI

We have recently bumped up our Android target api level from 23 to 24 and are now using the 24.2.0 Android support library. Our version of stetho is com.facebook.stetho:stetho:1.1.0 our version of stetho http is com.facebook.stetho:stetho-okhttp:1.1.0.

After the upgrade from support lib 23 to 24.2.0 on phones that are running api < 24 we get a crash of the app because the StethoInterceptor class can't be found in the class path. Below is the stack trace.

 **Process: com.fitnesskeeper.runkeeper.pro, PID: 14703
                                                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/stetho/okhttp/StethoInterceptor;
                                                                                     at com.fitnesskeeper.runkeeper.web.retrofit.RKWebClient.buildRequest(RKWebClient.java:131)
                                                                                     at com.fitnesskeeper.runkeeper.web.retrofit.RKWebClient.buildRequest(RKWebClient.java:113)**

We have also turned off pro-guard just to make sure that the StethoInterceptor class was not be obfuscated. The crash still persisted so I think we can rule out pro-guard as the culprit. Below is the code where this crash happens 

```
 try
        {
            OkHttpClient okHttpClient = new OkHttpClient();

            if (BuildConfig.DEBUG)
            {
                okHttpClient.networkInterceptors().add(new StethoInterceptor());
            }
```

I know we are on a old version of stetho. Have you guys heard of this type of issue with the version we are using and Android api level 24 and up?

thanks

**Comment by jasta** [comment]
Hmm, this seems like it might be some kind of bizarre proguard or build tools interaction?  Can you look at your binary using dexdump and try to confirm that the class is indeed in the APK or not?  If it's not, check your debug builds and go back even further to look into whether the stetho jars are getting linked into your app...

**Comment by jasta** [comment]
Cleaning up our task queue...
